services:
  db:
    image: postgres:17
    container_name: coursehub-db
    restart: always
    env_file:
      - .env
    ports:
      - "5431:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  coursehub:
    build: .
    container_name: coursehub-app
    env_file:
      - .env
    ports:
      - "8080:8080"
      - "5005:5005"
    depends_on:
      - db

volumes:
  db_data:
